# Generated by Django 5.1.1 on 2024-09-20 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='username',
            field=models.CharField(default='john', max_length=150, unique=True),
            preserve_default=False,
        ),
    ]
